### ISSUE TITLE
Lower NuGet requirement to 2.8.1

### ISSUE THREAD

**Issue by jamesmontemagno** [ufuf/AdvancedTimer#1]
Hey there! There was a bug in my templates (I have since updated them), but 2.8.1 is what is in Xamarin Studio, so you if you can modify and re-upload the nuspec that would be great.

Thanks!
James

**Comment by ufuf** [comment]
It was 2.8.1 in template but I changed it because of hangouts video ;)
I don't have my mac build host with me but I think VS do not need that.
I uploaded 1.0.0.1 version to nuget.
Best,
Ufuk ARSLAN

**Comment by jamesmontemagno** [comment]
Ahhh perfect, yeah that was my fault. I found out about 2.8.1 later. I will
leave a comment on the video :) Yeah you don't need a build host to
compile, only to test and deploy.

Thanks!

On Mon, Jan 5, 2015 at 5:07 PM, Ufuk ARSLAN notifications@github.com
wrote:

> It was 2.8.1 in template but I changed it because of hangouts video ;)
> I don't have my mac build host with me but I think VS do not need that.
> I uploaded 1.0.0.1 version to nuget.
> Best,
> Ufuk ARSLAN
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ufuf/AdvancedTimer/issues/1#issuecomment-68790829.

## 

James Montemagno
http://www.montemagno.com
@jamesmontemagno http://www.twitter.com/jamesmontemagno
