### ISSUE TITLE
Need Reset option

### ISSUE THREAD

**Issue by TravyDale** [ufuf/AdvancedTimer#10]
I need to use the timer in different view models. I am in need of a way to reset the timer so I can set it up for the other view model when it is active. In other words, I want to set my local method as the EventHandler for when the timer ticks. Or if I can get a new instance of the timer, that would be good too but I am unsure how to do that.

**Comment by ufuf** [comment]
I think what you are trying to do is related to [https://github.com/ufuf/AdvancedTimer/issues/9](https://github.com/ufuf/AdvancedTimer/issues/9)
You can try the solution as IAdvancedTimer timer = DependencyService.Get (DependencyFetchTarget.NewInstance);

**Comment by TravyDale** [comment]
Ok thanks. I will try that. I assumed there was a way to get a new instance.
