### ISSUE TITLE
unable to install nuget package

### ISSUE THREAD

**Issue by jmeadecvlt** [ufuf/AdvancedTimer#11]
Could not install package 'Mobilist.AdvancedTimer.Forms.Plugin 1.0.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by Greg767** [comment]
Exactly the same problem! I had this package in my PCL project but I needed to uninstall it and now I cannot reinstall!!! Please HELP!

**Comment by Greg767** [comment]
If I target PCL 4.5 - Profile78 it installs.
