### ISSUE TITLE
Crash on timerElapsed function

### ISSUE THREAD

**Issue by jonathanroze** [ufuf/AdvancedTimer#14]
Hello there,

i've implement your library, and its work great but i have problem, i call my function every 100 ms for test, and i have a popasync when my count is equal to 10 , so, 10 tick and my view back to parent ! 

But when i want to pop i have crash ! 

My code below : 

```
    public async void updateChrono(object sender, EventArgs e)
    {

        minuteLeftPoc++;
        System.Diagnostics.Debug.WriteLine(minuteLeftPoc);

        if (minuteLeftPoc == ((10))){

                    timer.stopTimer();
                    await APISession.closeSession(qrcode);
                    await APIPoc.closePoc(qrcode);



            System.Diagnostics.Debug.WriteLine("Temps écoulé");
            await Navigation.PopAsync();
        }
    }
```

**Comment by jonathanroze** [comment]
<img width="561" alt="capture d ecran 2016-07-01 a 10 12 09" src="https://cloud.githubusercontent.com/assets/2753799/16515782/4e16cb2a-3f74-11e6-9798-9a075dce3aa8.png">

**Comment by ufuf** [comment]
It may be a threading problem.
Timer is working on another thread and I am not sure if you are permitted to Pop from that thread.
You may use MessagingCenter for notifying the main thread for Navigation Pop.

**Comment by jonathanroze** [comment]
you're right!  My problem is solve i using  : Device.BeginInvokeOnMainThread

**Comment by ufuf** [comment]
It is an option but not the best practice ;)

**Comment by jonathanroze** [comment]
Yes you're right, with MesseagingCenter it's more clean :) !
