### ISSUE TITLE
Could not install Package 

### ISSUE THREAD

**Issue by deanilvincent** [ufuf/AdvancedTimer#15]
Could not install package 'Mobilist.AdvancedTimer.Forms.Plugin 1.0.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by vprysiazhnyi** [comment]
Same problem

**Comment by shehperd** [comment]
Same problem for me. After a few trial, I find AdvancedTimer can be installed on PCL target profile 78. To change the target profile, go to PCL project properties and change its target platforms. Consult the link below to select proper targets for the profile:
http://danrigby.com/2014/05/14/supported-pcl-profiles-xamarin-for-visual-studio-2/

If this still not work properly, try the method recommended by ylemsoul in the post below. It has satisfied my requirement.
https://forums.xamarin.com/discussion/49492/how-can-i-stop-device-starttimer

**Comment by AmitSrivastavGitHub** [comment]
Could not install package 'Mobilist.AdvancedTimer.Forms.Plugin 1.0.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

same issue i am also facing while installing the package .
and it get installed in the native repository.

**Comment by VahidShir** [comment]
I had the same problem.
I removed ASP.NET Core 1.0 from targets and the package installed successfully.
