### ISSUE TITLE
Can give more Explanation?

### ISSUE THREAD

**Issue by cheahengsoon** [ufuf/AdvancedTimer#18]
May I ask about this few line of code?

timer.initTimer(300, timerElapsed, false);

&

timer.setInterval(timer.getInterval() + 1000);

Where to Set the timer for Minute and Hours?

Thank You.

**Comment by ufuf** [comment]
@cheahengsoon you can set the interval as milliseconds. If you'll need to add an hour then you can use 3600000 instead of 1000.
Best
Ufuk
