### ISSUE TITLE
Adding this library on top of XLabs 2.0 breaks the WP project 

### ISSUE THREAD

**Issue by supreettare** [ufuf/AdvancedTimer#6]
Adding this library on top of XLabs 2.0 breaks the WP project

**Comment by ufuf** [comment]
Did you added it through nuget? Or did you add code from github?

**Comment by supreettare** [comment]
via Nuget

**Comment by ufuf** [comment]
There is a problem with nuget library right now. It also causes crash on iOS.
I will update it when I'm available.
For now you can clone code from github to your project.

**Comment by supreettare** [comment]
I see. Thanks for your support.
