### ISSUE TITLE
multiple timers at the same time clash

### ISSUE THREAD

**Issue by RogerSchmidlin** [ufuf/AdvancedTimer#9]
I am trying to run multiple timers at same time. Is this supposed to work? The events of the second timer don't seem to fire.

**Comment by ufuf** [comment]
It should be working. We were using it for 3 timers at the same time.

**Comment by RogerSchmidlin** [comment]
This is my code: Timer2 never fires an event. Maybe I am using it the wrong way.
I am using NuGet version 1.0.1.0
'
    public class MainView : ContentPage
    {
        IAdvancedTimer _timer1;
        IAdvancedTimer _timer2;

```
    void Timer1(object sender, EventArgs e)
    {
        Debug.WriteLine ("Timer1 is up");
    }
    void Timer2(object sender, EventArgs e)
    {
        Debug.WriteLine ("Timer2 is up");
    }

    public MainView ()
    {
        // timer for the video controller timeout to hide the custom controls
        _timer1 = DependencyService.Get<IAdvancedTimer> ();
        _timer1.initTimer (1000, Timer1, true);
        _timer1.startTimer ();

        // timer for slider update on video position
        _timer2 = DependencyService.Get<IAdvancedTimer> ();
        _timer2.initTimer (2000, Timer2, true);
        _timer2.startTimer ();

        Button doneButton = new Button {    Text = "Done" };
        StackLayout stacklayout = new StackLayout ();
        stacklayout.Children.Add (doneButton);

        this.Content = stacklayout;
    }
}
```

'

**Comment by RogerSchmidlin** [comment]
I found the problem with my code: The dependency service returns a singleton by default. Here the correct call to the platform instance:
IAdvancedTimer timer = DependencyService.Get<IAdvancedTimer> (DependencyFetchTarget.NewInstance);
